version: "3.8"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes: ['./:/usr/src/app']
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    logging: 
      driver: none
    ports:
      - "27017:27017"
